<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.chromia</groupId>
        <artifactId>chromia-parent</artifactId>
        <version>0.1.6</version>
    </parent>

    <groupId>net.postchain</groupId>
    <artifactId>ai-inference-extension</artifactId>
    <version>${revision}</version>

    <name>ai-inference-extension</name>
    <description>Extension for making inference with an AI model</description>

    <properties>
        <revision>dev</revision>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <kotlin.version>2.0.0</kotlin.version>
        <kotlin.compiler.jvmTarget>21</kotlin.compiler.jvmTarget>
        <kotlin.code.style>obsolete</kotlin.code.style> <!-- Kotlin obsolete IntelliJ IDEA codestyle -->

        <postchain.version>3.28.8</postchain.version>
        <postchain.chromia.version>3.27.4</postchain.chromia.version>
        <rell.version>0.14.5</rell.version>
        <rell.maven.plugin.version>0.14.1</rell.maven.plugin.version>
        <eif.version>0.13.1</eif.version>

        <djl.version>0.32.0</djl.version>

        <!--suppress UnresolvedMavenProperty -->
        <gitlab.username>${CI_REGISTRY_USER}</gitlab.username>
        <!--suppress UnresolvedMavenProperty -->
        <gitlab.password>${CI_REGISTRY_PASSWORD}</gitlab.password>
        <gitlab.registry>registry.gitlab.com/chromaway/core/ai-inference-extension</gitlab.registry>
        <docker.cache>/tmp/docker-cache</docker.cache>
        <image.platforms>linux/amd64</image.platforms>
        <image.name>chromaway/ai-inference-extension-chromia-subnode</image.name>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>postchain</artifactId>
                <version>${postchain.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-bom</artifactId>
                <version>${kotlin.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>ai.djl</groupId>
                <artifactId>bom</artifactId>
                <version>${djl.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>${kotlin.version}</version>
        </dependency>

        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-spi</artifactId>
        </dependency>

        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>chromia-infrastructure</artifactId>
            <version>${postchain.chromia.version}</version>
        </dependency>

        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.huggingface</groupId>
            <artifactId>tokenizers</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-model-zoo</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-engine</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-native-cpu</artifactId>
            <classifier>linux-x86_64</classifier>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-jni</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- logging -->
        <dependency>
            <groupId>io.github.microutils</groupId>
            <artifactId>kotlin-logging-jvm</artifactId>
        </dependency>

        <!-- Docker image dependencies -->
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-server-cli</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-web-static</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-gtx</artifactId>
            <version>${rell.version}</version>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-eif-core</artifactId>
            <version>${eif.version}</version>
        </dependency>

        <!-- Docker image and test dependencies -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
        </dependency>
        <!-- For Log4j2/YAML configuration -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-devtools</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <configuration>
                    <includes>
                        <include>**/*IT.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-maven-plugin</artifactId>
                <version>${rell.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <id>rell install</id>
                        <goals>
                            <goal>rell-install</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>rell-client-gen</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>rell-generate-client</goal>
                        </goals>
                        <configuration>
                            <packageName>net.postchain.gtx.extensions.ai_inference.rell</packageName>
                            <mainModules>
                                <mainModule>lib.ai_inference</mainModule>
                            </mainModules>
                        </configuration>
                    </execution>
                    <execution>
                        <id>rell compile</id>
                        <goals>
                            <goal>rell-compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>rell-test</id>
                        <phase>test</phase>
                        <goals>
                            <goal>rell-integration-test</goal>
                        </goals>
                        <configuration>
                            <skip>${skipTests}</skip>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.4.4</version>
                <configuration>
                    <allowInsecureRegistries>false</allowInsecureRegistries>
                    <from>
                        <image>
                            registry.gitlab.com/chromaway/core-tools/chromia-images/java21-postgres16-ubuntu:1.0.0@sha256:850a1f04c8f276df281b79246ffedeb70a6d78781675d160ac5d45f50c81c117
                        </image>
                    </from>
                    <to>
                        <image>${image.name}</image>
                    </to>
                    <container>
                        <appRoot>/opt/chromaway/postchain</appRoot>
                        <workingDirectory>/opt/chromaway/postchain</workingDirectory>
                        <entrypoint>/bin/bash</entrypoint>
                        <args>entrypoint.sh</args>
                        <environment>
                            <POSTCHAIN_RUNNING_IN_CONTAINER>true</POSTCHAIN_RUNNING_IN_CONTAINER>
                            <LOG4J_CONFIGURATION_FILE>/opt/chromaway/postchain/log4j2.yml</LOG4J_CONFIGURATION_FILE>
                            <POSTCHAIN_DIR>/opt/chromaway/postchain</POSTCHAIN_DIR>
                            <POSTGRES_DB>postchain</POSTGRES_DB>
                            <POSTGRES_USER>postchain</POSTGRES_USER>
                            <POSTGRES_PASSWORD>postchain</POSTGRES_PASSWORD>
                            <POSTGRES_INITDB_ARGS>--lc-collate=C.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8</POSTGRES_INITDB_ARGS>
                            <PGDATA>/var/lib/postgresql/data</PGDATA>
                            <DJL_CACHE_DIR>/tmp/djl.ai</DJL_CACHE_DIR>
                            <HF_HOME>/tmp/huggingface</HF_HOME>
                        </environment>
                        <creationTime>${git.commit.time}</creationTime>
                        <filesModificationTime>${git.commit.time}</filesModificationTime>
                    </container>
                    <containerizingMode>packaged</containerizingMode>
                </configuration>
                <executions>
                    <execution>
                        <id>docker-tar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>buildTar</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>docker-build</id>
                        <phase>install</phase>
                        <goals>
                            <goal>dockerBuild</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>docker-push</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.google.cloud.tools</groupId>
                        <artifactId>jib-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>deploy</phase>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                                <configuration>
                                    <from>
                                        <platforms>
                                            <platform>
                                                <architecture>amd64</architecture>
                                                <os>linux</os>
                                            </platform>
                                        </platforms>
                                    </from>
                                    <to>
                                        <image>${gitlab.registry}/${image.name}:${project.version}</image>
                                        <auth>
                                            <username>${env.CI_REGISTRY_USER}</username>
                                            <password>${env.CI_REGISTRY_PASSWORD}</password>
                                        </auth>
                                    </to>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <repositories>
        <repository>
            <id>chromia-parent</id>
            <name>Chromia parent GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/50818999/packages/maven</url>
        </repository>
        <repository>
            <id>postchain</id>
            <name>Postchain GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/32294340/packages/maven</url>
        </repository>
        <repository>
            <id>postchain-chromia</id>
            <name>Postchain Chromia GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/33481005/packages/maven</url>
        </repository>
        <repository>
            <id>rell</id>
            <name>Rell Registry</name>
            <url>https://gitlab.com/api/v4/projects/32802097/packages/maven</url>
        </repository>
        <repository>
            <id>postchain-eif</id>
            <name>Postchain EIF Gtx module Registry</name>
            <url>https://gitlab.com/api/v4/projects/36768178/packages/maven</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>rellmaven</id>
            <url>https://gitlab.com/api/v4/projects/37668820/packages/maven</url>
        </pluginRepository>
    </pluginRepositories>

    <distributionManagement>
        <repository>
            <id>gitlab-maven</id>
            <url>https://gitlab.com/api/v4/projects/67950851/packages/maven</url>
        </repository>
        <snapshotRepository>
            <id>gitlab-maven</id>
            <url>https://gitlab.com/api/v4/projects/67950851/packages/maven</url>
        </snapshotRepository>
    </distributionManagement>
</project>
